services:
  - type: web
    name: fashion-ai-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
